name: tmbiz
description: "TMBIZ"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  app_ui:
    path: ./packages/app_ui

  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  data_provider:
    path: ./packages/data_provider
  equatable: ^2.0.5
  firebase_messaging: ^14.7.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_local_notifications: ^16.2.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10
  go_router: ^12.1.3
  hydrated_bloc: ^9.1.2
  intl: ^0.18.1
  package_info_plus: ^4.2.0
  path_provider: ^2.1.1
  persistent_storage:
    path: ./packages/storage/persistent_storage
  secure_storage:
    path: ./packages/storage/secure_storage
  shared_preferences: ^2.2.0
  storage:
    path: ./packages/storage/storage
  form_inputs:
    path: ./packages/form_inputs
  cached_network_image: ^3.3.0
  phosphor_flutter: ^2.0.1
  shimmer: ^3.0.0
  flutter_hooks: ^0.20.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  turkmen_localization_support: ^0.0.7
  video_player: ^2.8.6

dev_dependencies:
  build_runner: ^2.4.6
  envied_generator: ^0.3.0+3
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/nav/
    - assets/videos/

dependency_overrides:
  intl: ^0.18.1

flutter_gen:
  assets:
    enabled: true
    outputs:
      class_name: TmbizAssets
      # package_parameter_enabled: true
  output: lib/generated/
  line_length: 80

  integrations:
    flutter_svg: true

  