name: app_ui
description: App UI Component Library
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.5
  google_fonts: ^5.1.0
  intl: ^0.18.0

dev_dependencies:
  build_runner: ^2.0.3
  flutter_gen_runner: ^5.2.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/Mulish/
    - assets/fonts/Mulish/static/
    - assets/fonts/Plus_Jakarta_Sans/
    - assets/fonts/Plus_Jakarta_Sans/static/
    # - assets/images/
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-Regular.ttf
  #         weight: 400

flutter_gen:
  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true
  output: lib/src/generated/
  line_length: 80

  integrations:
    flutter_svg: true
