name: data_provider
description: A package which handle 3rd layer data from out.
publish_to: none

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  dio: ^5.4.0
  equatable: ^2.0.5
  hive: ^2.2.3
  intl: ^0.18.1
  json_annotation: ^4.8.1
  pretty_dio_logger: ^1.3.1
  uuid: ^4.4.0

dev_dependencies:
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  test: ^1.21.4
  very_good_analysis: ^5.0.0+1
